### ISSUE TITLE
HTTP Injector

### ISSUE THREAD

**Issue by ahdezdev** [OpenBAS-Platform/openbas#1898]
## Description

I want to confirm whether OpenBAS supports HTTP Injector for managing custom HTTP payloads. If supported, I need guidance on implementing this functionality on a local development machine.

**Comment by RomuDeuxfois** [comment]
Hi, HTTP injector is not used for HTTP payloads. It's only used to do some API CALL (Get, Post, ect.)
You should be able to create a custom payload to do HTTP payloads.

Can you send me an example of what you want to achieve ?

**Comment by ahdezdev** [comment]
I am working on creating a news, event or simulation that triggers an HTTP POST request to an external API. The response should return a configurable JSON object containing two values: title and text. I have been doing some research and have discovered that HTTP Query Injector exists. However, I have two questions regarding its use:

Both in the OpenBAS demo and in my localhost project, the HTTP Query Injector does not appear. How can I activate or implement it?
Does this injector support the use case I described (send a POST request and handle the returned JSON with title and text)?

**Comment by RomuDeuxfois** [comment]
⚠ We found a critical issue on our tests
https://github.com/OpenBAS-Platform/openbas/issues/1903
It will be resolved in the next minor release.

How to use HTTP Injector

1. Be sure RabbitMQ is enabled and add the HTTP injector on your docker compose
```
  injector-http:
    image: openbas/injector-http-query:1.8.2
    environment:
      - OPENBAS_URL=http://openbas:8080
      - OPENBAS_TOKEN=${OPENBAS_ADMIN_TOKEN}
      - INJECTOR_ID=${INJECTOR_HTTP_QUERY} # Valid UUIDv4
      - INJECTOR_NAME=Injector Http Query
    restart: always
    depends_on:
      - openbas
```

2. You will see your new injector here
![Image](https://github.com/user-attachments/assets/636efddb-f267-4a8f-ba6a-57a1fe13e4b1)

3. Now, you can create an inject based on this injector
![Image](https://github.com/user-attachments/assets/08b4fb44-3295-423d-8292-c69a5bbdedf7)

4. And this is the result
![Image](https://github.com/user-attachments/assets/89d63411-1397-4b9a-b40a-df402d982235)

Does this meet your needs?
