### ISSUE TITLE
Caldera error url

### ISSUE THREAD

**Issue by Aquariius** [OpenBAS-Platform/openbas#2195]
## Environment

1. OS (where OpenBAS server runs): { e.g. Mac OS 10, Windows 10, Ubuntu 16.4, etc. }
Ubuntu 24.04 Docker
2. OpenBAS version: { e.g. OpenBAS 1.0.2 }
1.10.1

Bug:
I started the caldera server for Openbas
  caldera:
    image: openbas/caldera-server:5.0.0
    restart: always
    ports:
      - "8888:8888"
    environment:
      CALDERA_URL: http://caldera.domain.com:8888
    volumes:
      - type: bind
        source: caldera.yml
        target: /usr/src/app/conf/local.yml
openbas:
  image: openbas/platform:1.10.1
  environment:
    - SERVER_SSL_KEY-STORE-PASSWORD=${KEYSTORE_PASSWORD}
    - OPENBAS_BASE-URL=http://localhost:8080
    - OPENBAS_AUTH-LOCAL-ENABLE=true
    - SPRING_DATASOURCE_URL=jdbc:postgresql://pgsql:5432/openbas
    - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
    - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
    - MINIO_ENDPOINT=minio
    - MINIO_ACCESS-KEY=${MINIO_ROOT_USER}
    - MINIO_ACCESS-SECRET=${MINIO_ROOT_PASSWORD}
    - OPENBAS_RABBITMQ_HOSTNAME=rabbitmq
    - OPENBAS_RABBITMQ_USER=${RABBITMQ_DEFAULT_USER}
    - OPENBAS_RABBITMQ_PASS=${RABBITMQ_DEFAULT_PASS}
    - SPRING_MAIL_HOST=${SPRING_MAIL_HOST}
    - SPRING_MAIL_PORT=${SPRING_MAIL_PORT}
    - SPRING_MAIL_USERNAME=${SPRING_MAIL_USERNAME}
    - SPRING_MAIL_PASSWORD=${SPRING_MAIL_PASSWORD}
    - SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH}
    - SPRING_MAIL_PROPERTIES_MAIL_SMTP_SSL_ENABLE=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_SSL_ENABLE}
    - SPRING_MAIL_PROPERTIES_MAIL_SMTP_SSL_TRUST=*
    - SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE}
    - OPENBAS_MAIL_IMAP_ENABLED=${OPENBAS_MAIL_IMAP_ENABLED}
    - OPENBAS_MAIL_IMAP_HOST=${OPENBAS_MAIL_IMAP_HOST}
    - OPENBAS_MAIL_IMAP_PORT=${OPENBAS_MAIL_IMAP_PORT}
    - OPENBAS_MAIL_IMAP_USERNAME=${SPRING_MAIL_USERNAME}
    - OPENBAS_MAIL_IMAP_PASSWORD=${SPRING_MAIL_PASSWORD}
    - OPENBAS_MAIL_IMAP_AUTH=${OPENBAS_MAIL_IMAP_AUTH}
    - OPENBAS_MAIL_IMAP_SSL_ENABLE=${OPENBAS_MAIL_IMAP_SSL_ENABLE}
    - OPENBAS_MAIL_IMAP_SSL_TRUST=*
    - OPENBAS_MAIL_IMAP_STARTTLS_ENABLE=${OPENBAS_MAIL_IMAP_STARTTLS_ENABLE}
    - OPENBAS_ADMIN_EMAIL=${OPENBAS_ADMIN_EMAIL}
    - OPENBAS_ADMIN_PASSWORD=${OPENBAS_ADMIN_PASSWORD}
    - OPENBAS_ADMIN_TOKEN=${OPENBAS_ADMIN_TOKEN}
    - OPENBAS_XTM_OPENCTI_ENABLE=true
    - OPENBAS_XTM_OPENCTI_URL=http://opencti:8080
    - OPENBAS_XTM_OPENCTI_TOKEN=REDACTED
    - EXECUTOR_CALDERA_ENABLE=true
    - EXECUTOR_CALDERA_URL="http://caldera:8888"
    - EXECUTOR_CALDERA_PUBLIC-URL=http://caldera.domain.com:8888
    - EXECUTOR_CALDERA_API-KEY=REDACTED
But openbas always says this:

openbas-1  | Standard Commons Logging discovery in action with spring-jcl: please remove commons-logging.jar from classpath in order to avoid potential conflicts
openbas-1  | {"sequenceNumber":0,"timestamp":1736565116145,"nanoseconds":145300763,"level":"ERROR","threadName":"main","loggerName":"io.openbas.executors.caldera.service.CalderaExecutorService","context":{"name":"default","birthdate":1736565074004,"properties":{}},"mdc": {},"message":"Error creating caldera executor: java.lang.IllegalArgumentException: Illegal character in scheme name at index 0: \"http:\/\/caldera:8888\"\/api\/v2\/abilities","throwable":null}
openbas-1  | {"sequenceNumber":0,"timestamp":1736565116185,"nanoseconds":185491132,"level":"ERROR","threadName":"main","loggerName":"io.openbas.executors.caldera.service.CalderaExecutorService","context":{"name":"default","birthdate":1736565074004,"properties":{}},"mdc": {},"message":"Error creating caldera executor: java.lang.IllegalArgumentException: Illegal character in scheme name at index 0: \"http:\/\/caldera:8888\"\/api\/v2\/abilities","throwable":null}

Step i tried
1. puttitng - EXECUTOR_CALDERA_URL="http://caldera:8888", - EXECUTOR_CALDERA_URL=http://caldera:8888, - "EXECUTOR_CALDERA_URL=http://caldera:8888"
2. removing port but now cant connect

**Comment by RomuDeuxfois** [comment]
Hi,
Firstable, you need to remove the double quotes on the EXECUTOR_CALDERA_URL variable.
I keep going to investigate.

**Comment by RomuDeuxfois** [comment]
Can you tell me if you now have your executor present on this screen?
For my part it works now.

![Image](https://github.com/user-attachments/assets/22a3006a-4e16-41c2-bf65-984a219b2afb)

**Comment by RomuDeuxfois** [comment]
I replicated it this morning and am continuing to investigate further.

**Comment by RomuDeuxfois** [comment]
I'm not sure to understand the issue you're experiencing.  
Let me share my Docker Compose file and my Caldera yaml configuration file with you.  
Could you let me know if this helps?  

Docker-compose
```
version: '3'
services:
  pgsql:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: openbas
    volumes:
      - pgsqldata:/var/lib/postgresql/data
    restart: always
  minio:
    image: minio/minio:RELEASE.2024-05-28T17-19-04Z
    volumes:
      - s3data:/data
    ports:
      - "9000:9000"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data
    restart: always
  rabbitmq:
    image: rabbitmq:3.13-management
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
      - RABBITMQ_NODENAME=rabbit01@localhost
    volumes:
      - amqpdata:/var/lib/rabbitmq
    restart: always
  caldera:
    image: openbas/caldera-server:5.0.0
    restart: always
    ports:
      - "8888:8888"
    environment:
      CALDERA_URL: http://caldera.domain.com:8888
    volumes:
      - type: bind
        source: caldera.yml
        target: /usr/src/app/conf/local.yml
  openbas:
    image: openbas/platform:alpha
    environment:
      - SERVER_SSL_KEY-STORE-PASSWORD=${KEYSTORE_PASSWORD}
      - OPENBAS_BASE-URL=http://localhost:8080
      - OPENBAS_AUTH-LOCAL-ENABLE=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://pgsql:5432/openbas
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - MINIO_ENDPOINT=minio
      - MINIO_ACCESS-KEY=${MINIO_ROOT_USER}
      - MINIO_ACCESS-SECRET=${MINIO_ROOT_PASSWORD}
      - OPENBAS_RABBITMQ_HOSTNAME=rabbitmq
      - OPENBAS_RABBITMQ_USER=${RABBITMQ_DEFAULT_USER}
      - OPENBAS_RABBITMQ_PASS=${RABBITMQ_DEFAULT_PASS}
      - SPRING_MAIL_HOST=${SPRING_MAIL_HOST}
      - SPRING_MAIL_PORT=${SPRING_MAIL_PORT}
      - SPRING_MAIL_USERNAME=${SPRING_MAIL_USERNAME}
      - SPRING_MAIL_PASSWORD=${SPRING_MAIL_PASSWORD}
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH}
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_SSL_ENABLE=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_SSL_ENABLE}
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_SSL_TRUST=*
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE}
      - OPENBAS_MAIL_IMAP_ENABLED=true
      - OPENBAS_MAIL_IMAP_HOST=${OPENBAS_MAIL_IMAP_HOST}
      - OPENBAS_MAIL_IMAP_PORT=${OPENBAS_MAIL_IMAP_PORT}
      - OPENBAS_MAIL_IMAP_USERNAME=${SPRING_MAIL_USERNAME}
      - OPENBAS_MAIL_IMAP_PASSWORD=${SPRING_MAIL_PASSWORD}
      - OPENBAS_MAIL_IMAP_AUTH=${OPENBAS_MAIL_IMAP_AUTH}
      - OPENBAS_MAIL_IMAP_SSL_ENABLE=${OPENBAS_MAIL_IMAP_SSL_ENABLE}
      - OPENBAS_MAIL_IMAP_SSL_TRUST=*
      - OPENBAS_MAIL_IMAP_STARTTLS_ENABLE=${OPENBAS_MAIL_IMAP_STARTTLS_ENABLE}
      - OPENBAS_ADMIN_EMAIL=${OPENBAS_ADMIN_EMAIL}
      - OPENBAS_ADMIN_PASSWORD=${OPENBAS_ADMIN_PASSWORD}
      - OPENBAS_ADMIN_TOKEN=${OPENBAS_ADMIN_TOKEN}
#      - INJECTOR_CALDERA_URL=http://caldera:8888
#      - INJECTOR_CALDERA_PUBLIC_URL=http://caldera.domain.com:8888
#      - INJECTOR_CALDERA_API_KEY=ChangeMe
      - EXECUTOR_CALDERA_ENABLE=true
      - EXECUTOR_CALDERA_URL=http://caldera:8888
      - EXECUTOR_CALDERA_PUBLIC_URL=http://caldera.domain.com:8888
      - EXECUTOR_CALDERA_API_KEY=ChangeMe
    ports:
      - "8080:8080"
    depends_on:
      - pgsql
      - minio
      - rabbitmq
    restart: always
  collector-mitre-attack:
    image: openbas/collector-mitre-attack:1.5.1
    environment:
      - OPENBAS_URL=http://openbas:8080
      - OPENBAS_TOKEN=${OPENBAS_ADMIN_TOKEN}
      - COLLECTOR_ID=${COLLECTOR_MITRE_ATTACK_ID} # Valid UUIDv4
      - "COLLECTOR_NAME=MITRE ATT&CK"
      - COLLECTOR_LOG_LEVEL=info
    restart: always
    depends_on:
      - openbas
  collector-atomic-red-team:
    image: openbas/collector-atomic-red-team:1.5.1
    environment:
      - OPENBAS_URL=http://openbas:8080
      - OPENBAS_TOKEN=${OPENBAS_ADMIN_TOKEN}
      - COLLECTOR_ID=${COLLECTOR_ATOMIC_RED_TEAM_ID} # Valid UUIDv4
      - "COLLECTOR_NAME=Atomic Red Team"
      - COLLECTOR_LOG_LEVEL=info
    restart: always
    depends_on:
      - openbas
volumes:
  pgsqldata:
  s3data:
  amqpdata:

```
Caldera
```
users:
  red:
    red: ChangeMe                                                                     # Change this
  blue:
    blue: ChangeMe                                                                    # Change this
api_key_red: ChangeMe                                                                 # Change this
api_key_blue: ChangeMe                                                                # Change this
api_key: ChangeMe                                                                     # Change this
crypt_salt: ChangeMe                                                                  # Change this
encryption_key: ChangeMe                                                              # Change this
app.contact.http: http://caldera.domain.com:8888                                      # Change this
app.contact.tcp: 0.0.0.0:7010
app.contact.udp: 0.0.0.0:7011
app.contact.websocket: 0.0.0.0:7012
app.contact.dns.domain: localhost
app.contact.dns.socket: 0.0.0.0:53
app.contact.gist: API_KEY                                                             # Optional
app.contact.html: /weather                                                            # Optional
app.contact.slack.api_key: SLACK_TOKEN                                                # Optional
app.contact.slack.bot_id: SLACK_BOT_ID                                                # Optional
app.contact.slack.channel_id: SLACK_CHANNEL_ID                                        # Optional
app.contact.tunnel.ssh.host_key_file: REPLACE_WITH_KEY_FILE_PATH                      # Optional
app.contact.tunnel.ssh.host_key_passphrase: REPLACE_WITH_KEY_FILE_PASSPHRASE          # Optional
app.contact.tunnel.ssh.socket: 0.0.0.0:8022
app.contact.tunnel.ssh.user_name: sandcat
app.contact.tunnel.ssh.user_password: ChangeMe                                        # Change this
objects.planners.default: atomic
requirements:
  go:
    command: go version
    type: installed_program
    version: 1.11
  python:
    attr: version
    module: sys
    type: python_module
    version: 3.8.0
host: 0.0.0.0
port: 8888
ability_refresh: 60
plugins:
  - access
  - atomic
  - compass
  - debrief
  - fieldmanual
  - gameboard
  - manx
  - response
  - sandcat
  - stockpile
  - training

```

Thank you!
